#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum C0Control {
    Nul,
    Soh,
    Stx,
    Etx,
    Eot,
    Enq,
    Ack,
    Bell,
    Backspace,
    Tab,
    LineFeed,
    VerticalTab,
    FormFeed,
    CarriageReturn,
    So,
    Si,
    Dle,
    Dc1,
    Dc2,
    Dc3,
    Dc4,
    Nak,
    Syn,
    Etb,
    Can,
    Em,
    Sub,
    Escape,
    FileSeparator,
    GroupSeparator,
    RecordSeparator,
    UnitSeparator,
}

impl C0Control {
    pub fn from_byte(byte: u8) -> Option<Self> {
        Some(match byte {
            0x00 => Self::Nul,
            0x01 => Self::Soh,
            0x02 => Self::Stx,
            0x03 => Self::Etx,
            0x04 => Self::Eot,
            0x05 => Self::Enq,
            0x06 => Self::Ack,
            0x07 => Self::Bell,
            0x08 => Self::Backspace,
            0x09 => Self::Tab,
            0x0A => Self::LineFeed,
            0x0B => Self::VerticalTab,
            0x0C => Self::FormFeed,
            0x0D => Self::CarriageReturn,
            0x0E => Self::So,
            0x0F => Self::Si,
            0x10 => Self::Dle,
            0x11 => Self::Dc1,
            0x12 => Self::Dc2,
            0x13 => Self::Dc3,
            0x14 => Self::Dc4,
            0x15 => Self::Nak,
            0x16 => Self::Syn,
            0x17 => Self::Etb,
            0x18 => Self::Can,
            0x19 => Self::Em,
            0x1A => Self::Sub,
            0x1B => Self::Escape,
            0x1C => Self::FileSeparator,
            0x1D => Self::GroupSeparator,
            0x1E => Self::RecordSeparator,
            0x1F => Self::UnitSeparator,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum C1Control {
    Index,
    NextLine,
    HorizontalTabSet,
    ReverseIndex,
    SingleShift2,
    SingleShift3,
    DeviceControlString,
    PrivateUse1,
    PrivateUse2,
    StartOfString,
    ControlSequenceIntroducer,
    StringTerminator,
    OperatingSystemCommand,
    PrivacyMessage,
    ApplicationProgramCommand,
}

impl C1Control {
    pub fn from_byte(byte: u8) -> Option<Self> {
        Some(match byte {
            0x84 => Self::Index,
            0x85 => Self::NextLine,
            0x88 => Self::HorizontalTabSet,
            0x8D => Self::ReverseIndex,
            0x8E => Self::SingleShift2,
            0x8F => Self::SingleShift3,
            0x90 => Self::DeviceControlString,
            0x91 => Self::PrivateUse1,
            0x92 => Self::PrivateUse2,
            0x98 => Self::StartOfString,
            0x9B => Self::ControlSequenceIntroducer,
            0x9C => Self::StringTerminator,
            0x9D => Self::OperatingSystemCommand,
            0x9E => Self::PrivacyMessage,
            0x9F => Self::ApplicationProgramCommand,
            _ => return None,
        })
    }
}
