//! Events generated by the flow subsystem.

use std::time::SystemTime;

use super::{
    edge::EdgeId,
    node::FlowNodeId,
};

#[derive(Debug, Clone)]
pub enum FlowEventKind {
    NodeCreated,
    NodeRemoved,
    EdgeCreated,
    EdgeRemoved,
    DataInput {
        bytes: usize,
    },
    DataOutput {
        bytes: usize,
    },
    ProcessStarted,
    ProcessExited {
        status: Option<i32>,
    },
    PtyResized {
        rows: u16,
        columns: u16,
    },
    TerminalFocused,
    TerminalUnfocused,
    PaneFocused,
    PaneUnfocused,
    StateChanged,
}

#[derive(Debug, Clone)]
pub struct FlowEvent {
    sequence: u64,
    timestamp: SystemTime,
    source: Option<FlowNodeId>,
    target: Option<FlowNodeId>,
    edge: Option<EdgeId>,
    kind: FlowEventKind,
}

impl FlowEvent {
    pub fn new(sequence: u64, kind: FlowEventKind) -> Self {
        Self {
            sequence,
            timestamp: SystemTime::now(),
            source: None,
            target: None,
            edge: None,
            kind,
        }
    }

    pub fn sequence(&self) -> u64 {
        self.sequence
    }

    pub fn timestamp(&self) -> SystemTime {
        self.timestamp
    }

    pub fn source(&self) -> Option<FlowNodeId> {
        self.source
    }

    pub fn target(&self) -> Option<FlowNodeId> {
        self.target
    }

    pub fn edge(&self) -> Option<EdgeId> {
        self.edge
    }

    pub fn kind(&self) -> &FlowEventKind {
        &self.kind
    }

    pub fn with_source(mut self, source: FlowNodeId) -> Self {
        self.source = Some(source);
        self
    }

    pub fn with_target(mut self, target: FlowNodeId) -> Self {
        self.target = Some(target);
        self
    }

    pub fn with_edge(mut self, edge: EdgeId) -> Self {
        self.edge = Some(edge);
        self
    }
}
