//! Runtime shell integration.
//!
//! This module tracks a shell session without taking ownership of the PTY.
//! PTY lifecycle and terminal I/O remain responsibilities of Conduit's
//! PTY/terminal subsystems.

use std::time::{Duration, Instant};

use super::{
    capabilities::ShellCapabilities,
    configuration::ShellConfiguration,
    directory::DirectoryTracker,
    environment::Environment,
    manifest::ShellManifest,
    prompt::PromptIntegration,
};

/// Unique identifier for a shell integration instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ShellId(u64);

impl ShellId {
    pub fn new(value: u64) -> Self {
        Self(value)
    }

    pub fn value(self) -> u64 {
        self.0
    }
}

/// Runtime shell state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ShellState {
    Created,
    Starting,
    Running,
    Suspended,
    Exited,
    Failed,
}

impl Default for ShellState {
    fn default() -> Self {
        Self::Created
    }
}

/// Events generated by shell integration.
#[derive(Debug, Clone)]
pub enum ShellEvent {
    Started,
    PromptShown,
    CommandStarted {
        command: String,
    },
    CommandFinished {
        status: Option<i32>,
        duration: Option<Duration>,
    },
    DirectoryChanged {
        path: std::path::PathBuf,
    },
    EnvironmentChanged,
    Exited {
        status: Option<i32>,
    },
    Failed {
        message: String,
    },
}

/// Errors from shell integration.
#[derive(Debug)]
pub enum ShellError {
    InvalidState(String),
    InvalidConfiguration(String),
    Io(std::io::Error),
    Manifest(String),
}

impl std::fmt::Display for ShellError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::InvalidState(message) => write!(f, "{message}"),
            Self::InvalidConfiguration(message) => {
                write!(f, "{message}")
            }
            Self::Io(error) => write!(f, "{error}"),
            Self::Manifest(error) => write!(f, "{error}"),
        }
    }
}

impl std::error::Error for ShellError {}

impl From<std::io::Error> for ShellError {
    fn from(error: std::io::Error) -> Self {
        Self::Io(error)
    }
}

/// Runtime integration state for one shell session.
#[derive(Debug)]
pub struct ShellIntegration {
    id: ShellId,
    manifest: ShellManifest,
    configuration: ShellConfiguration,
    capabilities: ShellCapabilities,

    state: ShellState,

    environment: Environment,
    directory: DirectoryTracker,
    prompt: PromptIntegration,

    started_at: Option<Instant>,
    last_command_started: Option<Instant>,
    last_exit_status: Option<i32>,
}

impl ShellIntegration {
    pub fn new(
        id: ShellId,
        manifest: ShellManifest,
        configuration: ShellConfiguration,
    ) -> Result<Self, ShellError> {
        manifest
            .validate()
            .map_err(|error| ShellError::Manifest(error.to_string()))?;

        let mut environment = if configuration.inherit_environment {
            Environment::from_current_process()
        } else {
            Environment::new()
        };

        for (key, value) in &manifest.environment {
            environment.set(key.clone(), value.clone());
        }

        for (key, value) in &configuration.environment {
            environment.set(key.clone(), value.clone());
        }

        let mut directory = DirectoryTracker::from_current();

        if let Some(path) = &configuration.working_directory {
            if !directory.update(path.clone()) {
                return Err(ShellError::InvalidConfiguration(
                    format!(
                        "invalid working directory: {}",
                        path.display()
                    ),
                ));
            }
        }

        let mut prompt = PromptIntegration::new();

        if !configuration.integrate_prompt {
            prompt.set_mode(super::prompt::PromptMode::Disabled);
        }

        Ok(Self {
            id,
            capabilities: manifest.capabilities.clone(),
            manifest,
            configuration,
            state: ShellState::Created,
            environment,
            directory,
            prompt,
            started_at: None,
            last_command_started: None,
            last_exit_status: None,
        })
    }

    pub fn id(&self) -> ShellId {
        self.id
    }

    pub fn manifest(&self) -> &ShellManifest {
        &self.manifest
    }

    pub fn configuration(&self) -> &ShellConfiguration {
        &self.configuration
    }

    pub fn capabilities(&self) -> &ShellCapabilities {
        &self.capabilities
    }

    pub fn state(&self) -> ShellState {
        self.state
    }

    pub fn environment(&self) -> &Environment {
        &self.environment
    }

    pub fn environment_mut(&mut self) -> &mut Environment {
        &mut self.environment
    }

    pub fn directory(&self) -> &DirectoryTracker {
        &self.directory
    }

    pub fn directory_mut(&mut self) -> &mut DirectoryTracker {
        &mut self.directory
    }

    pub fn prompt(&self) -> &PromptIntegration {
        &self.prompt
    }

    pub fn prompt_mut(&mut self) -> &mut PromptIntegration {
        &mut self.prompt
    }

    pub fn start(&mut self) -> Result<ShellEvent, ShellError> {
        if !matches!(
            self.state,
            ShellState::Created | ShellState::Exited | ShellState::Failed
        ) {
            return Err(ShellError::InvalidState(
                "shell cannot be started from its current state".into(),
            ));
        }

        self.state = ShellState::Starting;
        self.started_at = Some(Instant::now());
        self.last_command_started = None;
        self.last_exit_status = None;
        self.state = ShellState::Running;

        Ok(ShellEvent::Started)
    }

    pub fn suspend(&mut self) -> Result<(), ShellError> {
        if self.state != ShellState::Running {
            return Err(ShellError::InvalidState(
                "only a running shell can be suspended".into(),
            ));
        }

        self.state = ShellState::Suspended;
        Ok(())
    }

    pub fn resume(&mut self) -> Result<(), ShellError> {
        if self.state != ShellState::Suspended {
            return Err(ShellError::InvalidState(
                "only a suspended shell can be resumed".into(),
            ));
        }

        self.state = ShellState::Running;
        Ok(())
    }

    pub fn command_started(
        &mut self,
        command: impl Into<String>,
    ) -> Result<ShellEvent, ShellError> {
        if self.state != ShellState::Running {
            return Err(ShellError::InvalidState(
                "cannot start a command when the shell is not running"
                    .into(),
            ));
        }

        self.last_command_started = Some(Instant::now());

        Ok(ShellEvent::CommandStarted {
            command: command.into(),
        })
    }

    pub fn command_finished(
        &mut self,
        status: Option<i32>,
    ) -> Result<ShellEvent, ShellError> {
        if self.state != ShellState::Running {
            return Err(ShellError::InvalidState(
                "cannot finish a command when the shell is not running"
                    .into(),
            ));
        }

        let duration =
            self.last_command_started.map(|started| started.elapsed());

        self.last_command_started = None;
        self.last_exit_status = status;

        Ok(ShellEvent::CommandFinished { status, duration })
    }

    pub fn prompt_shown(&mut self) -> Result<ShellEvent, ShellError> {
        if self.state != ShellState::Running {
            return Err(ShellError::InvalidState(
                "cannot report a prompt when the shell is not running"
                    .into(),
            ));
        }

        Ok(ShellEvent::PromptShown)
    }

    pub fn directory_changed(
        &mut self,
        path: impl Into<std::path::PathBuf>,
    ) -> Option<ShellEvent> {
        let path = path.into();

        if self.directory.update(path.clone()) {
            Some(ShellEvent::DirectoryChanged { path })
        } else {
            None
        }
    }

    pub fn environment_changed(&self) -> ShellEvent {
        ShellEvent::EnvironmentChanged
    }

    pub fn exit(
        &mut self,
        status: Option<i32>,
    ) -> Result<ShellEvent, ShellError> {
        if self.state == ShellState::Exited {
            return Err(ShellError::InvalidState(
                "shell has already exited".into(),
            ));
        }

        self.state = ShellState::Exited;
        self.last_exit_status = status;

        Ok(ShellEvent::Exited { status })
    }

    pub fn fail(
        &mut self,
        message: impl Into<String>,
    ) -> ShellEvent {
        let message = message.into();

        self.state = ShellState::Failed;

        ShellEvent::Failed { message }
    }

    pub fn uptime(&self) -> Option<Duration> {
        self.started_at.map(|started| started.elapsed())
    }

    pub fn last_exit_status(&self) -> Option<i32> {
        self.last_exit_status
    }

    /// Construct the command used to launch this shell.
    pub fn launch_command(&self) -> std::process::Command {
        let executable = self
            .configuration
            .executable
            .clone()
            .unwrap_or_else(|| self.manifest.executable.clone());

        let mut command = std::process::Command::new(executable);

        command.args(self.configuration.launch_arguments());

        if let Some(directory) = &self.configuration.working_directory {
            command.current_dir(directory);
        }

        self.environment.apply(&mut command);

        command
    }
}
